config/routes.rb
Rails.application.routes.draw do
  root 'first_models#index'
  
  resources :first_models

end

app/models/first_model.rb
class FirstModel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/first_models_controller.rb
class FirstModelsController < ApplicationController
  before_action :set_first_model, only: [:show, :edit, :update, :destroy]

  # GET /first_models
  # GET /first_models.json
  def index
    @first_models = FirstModel.all
  end

  # GET /first_models/1
  # GET /first_models/1.json
  def show
  end

  # GET /first_models/new
  def new
    @first_model = FirstModel.new
  end

  # GET /first_models/1/edit
  def edit
  end

  # POST /first_models
  # POST /first_models.json
  def create
    @first_model = FirstModel.new(first_model_params)

    respond_to do |format|
      if @first_model.save
        format.html { redirect_to @first_model, notice: 'First model was successfully created.' }
        format.json { render :show, status: :created, location: @first_model }
      else
        format.html { render :new }
        format.json { render json: @first_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /first_models/1
  # PATCH/PUT /first_models/1.json
  def update
    respond_to do |format|
      if @first_model.update(first_model_params)
        format.html { redirect_to @first_model, notice: 'First model was successfully updated.' }
        format.json { render :show, status: :ok, location: @first_model }
      else
        format.html { render :edit }
        format.json { render json: @first_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /first_models/1
  # DELETE /first_models/1.json
  def destroy
    @first_model.destroy
    respond_to do |format|
      format.html { redirect_to first_models_url, notice: 'First model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_first_model
      @first_model = FirstModel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def first_model_params
      params.require(:first_model).permit(:foo, :bar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_models_helper.rb
module FirstModelsHelper
end

app/views/first_models/_form.html.erb
<%= form_for(@first_model) do |f| %>
  <% if @first_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@first_model.errors.count, "error") %> prohibited this first_model from being saved:</h2>

      <ul>
      <% @first_model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :foo %><br>
    <%= f.text_field :foo %>
  </div>
  <div class="field">
    <%= f.label :bar %><br>
    <%= f.text_field :bar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/first_models/edit.html.erb
<h1>Editing First Model</h1>

<%= render 'form' %>

<%= link_to 'Show', @first_model %> |
<%= link_to 'Back', first_models_path %>

app/views/first_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing First Models</h1>

<table>
  <thead>
    <tr>
      <th>Foo</th>
      <th>Bar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @first_models.each do |first_model| %>
      <tr>
        <td><%= first_model.foo %></td>
        <td><%= first_model.bar %></td>
        <td><%= link_to 'Show', first_model %></td>
        <td><%= link_to 'Edit', edit_first_model_path(first_model) %></td>
        <td><%= link_to 'Destroy', first_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New First model', new_first_model_path %>

app/views/first_models/new.html.erb
<h1>New First Model</h1>

<%= render 'form' %>

<%= link_to 'Back', first_models_path %>

app/views/first_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foo:</strong>
  <%= @first_model.foo %>
</p>

<p>
  <strong>Bar:</strong>
  <%= @first_model.bar %>
</p>

<%= link_to 'Edit', edit_first_model_path(@first_model) %> |
<%= link_to 'Back', first_models_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToMarvinj</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>